ALTER TABLE transparencia ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transparencia ADD COLUMN IF NOT EXISTS atualizado_por INTEGER REFERENCES funcionario(idfuncionario) ON DELETE RESTRICT;
